<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShopClient\ShopClient.csproj" />
      <ProjectReference Include="..\WebContracts\WebContracts.csproj" />
    </ItemGroup>

</Project>
