<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiClient\AiClient.csproj" />
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Products\ProductsReader.logger.cs">
      <DependentUpon>ProductsReader.cs</DependentUpon>
    </Compile>
    <Compile Update="Products\ProductsAiSearchService.logger.cs">
      <DependentUpon>ProductsSearchService.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
