// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217180111_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contracts.Brands.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ApexRidge"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TerraFlow"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ZenithPath"
                        });
                });

            modelBuilder.Entity("Contracts.Carts.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            StatusType = 1
                        });
                });

            modelBuilder.Entity("Contracts.Categories.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hiking Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Backpacks"
                        });
                });

            modelBuilder.Entity("Contracts.Customers.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.blue@example.ch",
                            UserName = "John Blue"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marry.green@example.ch",
                            UserName = "Marry Green"
                        });
                });

            modelBuilder.Entity("Contracts.Images.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "p1-tent-aura-2-ultralight",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "p2-tent-citadel-fortress-2",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "p2-tent-citadel-fortress-2-background",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "p3-tent-citadel-fortress-4",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "p4-shoes-vanguard-low-pro",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "p5-shoes-titan-claw-boots",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "p6-backpack-atlas-hauler-75l-blue",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "p6-backpack-atlas-hauler-75l-braun",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 9,
                            Name = "p6-backpack-atlas-hauler-75l-green",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "p7-backpack-swift-pulse-15l",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 11,
                            Name = "p8-backpack-nomad-versa-pack",
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("Contracts.Products.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Fictional ultralight tent for high-altitude camping.",
                            Name = "Aura 2 Ultralight",
                            Price = 315.00m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "A 2-person heavy-duty basecamp tent built for extreme conditions.",
                            Name = "Citadel Fortress 2",
                            Price = 285.99m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "A heavy-duty basecamp tent built for extreme conditions.",
                            Name = "Citadel Fortress 4",
                            Price = 485.99m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "Synthetic mesh trail runners for rapid elevation gain.",
                            Name = "Vanguard Low-Pro",
                            Price = 145.00m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            CategoryId = 2,
                            Description = "Reinforced leather boots for technical rocky scrambles.",
                            Name = "Titan-Claw Boots",
                            Price = 189.50m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            CategoryId = 3,
                            Description = "Expedition-grade pack with modular external storage.",
                            Name = "Atlas Hauler 75L",
                            Price = 265.00m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 3,
                            Description = "Minimalist hydration pack for peak bagging.",
                            Name = "Swift-Pulse 15",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            CategoryId = 3,
                            Description = "Roll-top waterproof backpack for the modern explorer.",
                            Name = "Nomad Versa-Pack",
                            Price = 99.00m
                        });
                });

            modelBuilder.Entity("Contracts.ProductsAiSearch.Entities.ProductEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Deployment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductEmbeddings");
                });

            modelBuilder.Entity("Contracts.ProductsCart.Entities.ProductCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BundlePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BundlePrice = 315.00m,
                            CartId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 315.00m
                        },
                        new
                        {
                            Id = 2,
                            BundlePrice = 150.00m,
                            CartId = 1,
                            ProductId = 7,
                            Quantity = 3,
                            UnitPrice = 75.00m
                        });
                });

            modelBuilder.Entity("Contracts.Reviews.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 14, 20, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = 1,
                            ProductId = 1,
                            Rating = 5,
                            Status = 1,
                            Text = "Great product!",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 2, 14, 20, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 15, 13, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = 2,
                            ProductId = 1,
                            Rating = 3,
                            Status = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 2, 16, 17, 34, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 16, 17, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = 2,
                            ProductId = 1,
                            Rating = 2,
                            Status = 1,
                            Text = "Too small for big people!",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 2, 16, 17, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Contracts.Carts.Entities.Cart", b =>
                {
                    b.HasOne("Contracts.Customers.Entities.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Contracts.Images.Entities.Image", b =>
                {
                    b.HasOne("Contracts.Products.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Contracts.Products.Entities.Product", b =>
                {
                    b.HasOne("Contracts.Brands.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contracts.Categories.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Contracts.ProductsAiSearch.Entities.ProductEmbedding", b =>
                {
                    b.HasOne("Contracts.Products.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Contracts.ProductsCart.Entities.ProductCart", b =>
                {
                    b.HasOne("Contracts.Carts.Entities.Cart", "Cart")
                        .WithMany("ProductCarts")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contracts.Products.Entities.Product", "Product")
                        .WithMany("ProductCarts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Contracts.Reviews.Entities.Review", b =>
                {
                    b.HasOne("Contracts.Customers.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contracts.Products.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Contracts.Brands.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Contracts.Carts.Entities.Cart", b =>
                {
                    b.Navigation("ProductCarts");
                });

            modelBuilder.Entity("Contracts.Categories.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Contracts.Customers.Entities.Customer", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("Contracts.Products.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
