@ShopServer_HostAddress = https://localhost:5051

###
GET {{ShopServer_HostAddress}}/health/
Accept: application/json

###
GET {{ShopServer_HostAddress}}/openapi/v1.json
Accept: application/json

###
# open in browser:
GET {{ShopServer_HostAddress}}/swagger/index.html

###
